"""Volatile, server-owned clarification state for Metis Brain.

The store in this module deliberately has no dependency on the HTTP server or
the concrete session manager.  A service can inject it at the orchestration
boundary and bind its lifecycle to a Brain session.  It retains only bounded
decision summaries; it never retains the operator's prompt or a transcript.
"""

from __future__ import annotations

import re
import secrets
import threading
import time
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from hashlib import sha256
from typing import Any, Literal

from metis_model1.brain_protocol import IDLE_TTL_SECONDS, BrainError, revision

ClarificationKind = Literal[
    "catalog",
    "semantic_choice",
    "result_count",
    "response_shape",
    "fallback",
]

CLARIFICATION_KINDS = frozenset(
    {"catalog", "semantic_choice", "result_count", "response_shape", "fallback"}
)
OPTION_KINDS = CLARIFICATION_KINDS - {"result_count"}
MAX_ROUNDS = 3
MAX_OPTIONS = 5
MAX_CATALOG_REFERENCES = 64
MAX_QUESTION_BYTES = 512
MAX_LABEL_BYTES = 256
MAX_DESCRIPTION_BYTES = 1024
MAX_VALUE_BYTES = 256
MAX_ASSUMPTION_BYTES = 512
MAX_QUESTION_KEY_BYTES = 128
MAX_PROPOSAL_REF_BYTES = 256
DEFAULT_MAX_RESULT_COUNT = 1000
MAX_CONVERSATIONS_PER_SESSION = 8
MAX_RETIRED_PER_SESSION = 32

_OPAQUE_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$")
_SESSION_ID_RE = re.compile(r"^[A-Za-z0-9_-]{32,96}$")
_TURN_ID_RE = re.compile(r"^[A-Za-z0-9_-]{24,96}$")
_QUESTION_KEY_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$")
_SHA256_RE = re.compile(r"^sha256:[0-9a-f]{64}$")


def _fail(code: str, status: int, message: str) -> None:
    raise BrainError(code, status, message)


def _bounded_text(value: Any, *, name: str, max_bytes: int) -> str:
    if not isinstance(value, str) or not value:
        _fail("INVALID_SCHEMA", 400, f"{name} must be a non-empty string")
    try:
        encoded = value.encode("utf-8")
    except UnicodeEncodeError as error:
        raise BrainError("INVALID_SCHEMA", 400, f"{name} must be UTF-8") from error
    if len(encoded) > max_bytes or any(ord(character) < 0x20 for character in value):
        _fail("INVALID_SCHEMA", 400, f"{name} is invalid or exceeds its byte limit")
    return value


def _opaque(value: Any, *, name: str, max_bytes: int = MAX_VALUE_BYTES) -> str:
    text = _bounded_text(value, name=name, max_bytes=max_bytes)
    if _OPAQUE_RE.fullmatch(text) is None:
        _fail("INVALID_SCHEMA", 400, f"{name} is invalid")
    return text


def clarification_reference(value: Any, *, name: str) -> str:
    """Validate the exact opaque-reference surface emitted on the public clarification wire."""

    return _opaque(value, name=name, max_bytes=MAX_VALUE_BYTES)


def clarification_text(value: Any, *, name: str = "catalog_ref") -> str:
    """Validate bounded operator text used only for catalog-roster selection."""

    text = _bounded_text(value, name=name, max_bytes=MAX_VALUE_BYTES)
    if not text.strip() or text != text.strip():
        _fail("INVALID_SCHEMA", 400, f"{name} must be exact non-blank text")
    return text


def _fingerprint(value: Any, *, name: str) -> str:
    text = _bounded_text(value, name=name, max_bytes=72)
    if _SHA256_RE.fullmatch(text) is None:
        _fail("INVALID_SCHEMA", 400, f"{name} is invalid")
    return text


def _question_key(value: Any) -> str:
    text = _bounded_text(value, name="question_key", max_bytes=MAX_QUESTION_KEY_BYTES)
    if _QUESTION_KEY_RE.fullmatch(text) is None:
        _fail("INVALID_SCHEMA", 400, "question_key is invalid")
    return text


def _validate_session_id(value: Any) -> str:
    text = _bounded_text(value, name="session_id", max_bytes=96)
    if _SESSION_ID_RE.fullmatch(text) is None:
        _fail("INVALID_SCHEMA", 400, "session_id is invalid")
    return text


def _validate_turn_id(value: Any) -> str:
    text = _bounded_text(value, name="parent_turn_id", max_bytes=96)
    if _TURN_ID_RE.fullmatch(text) is None:
        _fail("INVALID_SCHEMA", 400, "parent_turn_id is invalid")
    return text


@dataclass(frozen=True)
class ClarificationChoice:
    """A candidate supplied by the adjudicator, not a client-supplied ref."""

    label: str
    value: str | None = None
    description: str | None = None
    catalog: str | None = None

    def __post_init__(self) -> None:
        _bounded_text(self.label, name="option label", max_bytes=MAX_LABEL_BYTES)
        if self.value is not None:
            _bounded_text(self.value, name="option value", max_bytes=MAX_VALUE_BYTES)
        if self.description is not None:
            _bounded_text(
                self.description,
                name="option description",
                max_bytes=MAX_DESCRIPTION_BYTES,
            )
        if self.catalog is not None:
            _opaque(self.catalog, name="option catalog")


@dataclass(frozen=True)
class ClarificationOption:
    """Public option.  ``option_ref`` is generated by this store."""

    option_ref: str
    label: str
    description: str | None = None
    catalog: str | None = None

    def payload(self) -> dict[str, str]:
        result = {"option_ref": self.option_ref, "label": self.label}
        if self.description is not None:
            result["description"] = self.description
        if self.catalog is not None:
            result["catalog"] = self.catalog
        return result


@dataclass(frozen=True)
class ClarificationAnswer:
    kind: ClarificationKind
    option_ref: str | None = None
    integer: int | None = None
    text: str | None = None
    resolved_value: str | None = None

    def payload(self) -> dict[str, Any]:
        if self.kind == "result_count":
            return {"integer": self.integer}
        if self.text is not None:
            return {"text": self.text}
        return {"option_ref": self.option_ref}


@dataclass(frozen=True)
class ClarificationDecision:
    kind: ClarificationKind
    question_key: str
    round_index: int
    answer: ClarificationAnswer
    label: str | None = None

    def payload(self) -> dict[str, Any]:
        result: dict[str, Any] = {
            "kind": self.kind,
            "question_key": self.question_key,
            "round": self.round_index,
            "answer": self.answer.payload(),
        }
        if self.label is not None:
            result["label"] = self.label
        return result


@dataclass(frozen=True)
class PendingClarification:
    clarification_id: str
    session_id: str
    parent_turn_id: str
    request_fingerprint: str
    kind: ClarificationKind
    question_key: str
    question: str
    options: tuple[ClarificationOption, ...]
    context_revision: str
    semantic_source_revision: str
    round_index: int
    max_rounds: int
    expires_at: float
    catalog_refs: tuple[str, ...] = ()
    min_value: int | None = None
    max_value: int | None = None

    @property
    def answer_schema(self) -> dict[str, Any]:
        if self.kind == "result_count":
            return {
                "type": "integer",
                "minimum": self.min_value,
                "maximum": self.max_value,
            }
        if self.catalog_refs:
            return {
                "type": "text",
                "format": "catalog-ref",
                "max_bytes": MAX_VALUE_BYTES,
            }
        return {"type": "option_ref"}

    def payload(self, *, now: float | None = None) -> dict[str, Any]:
        remaining = self.expires_at - now if now is not None else None
        result: dict[str, Any] = {
            "clarification_id": self.clarification_id,
            "kind": self.kind,
            "question": self.question,
            "options": [option.payload() for option in self.options],
            "answer_schema": self.answer_schema,
            "round": self.round_index,
            "max_rounds": self.max_rounds,
        }
        if remaining is not None:
            result["expires_in_seconds"] = round(max(0.0, remaining), 3)
        if self.catalog_refs:
            result["catalog_refs"] = list(self.catalog_refs)
        return result


@dataclass(frozen=True)
class ConversationSummary:
    session_id: str
    request_fingerprint: str
    context_revision: str
    semantic_source_revision: str
    rounds_used: int
    max_rounds: int
    decisions: tuple[ClarificationDecision, ...]
    assumptions: tuple[str, ...]
    latest_proposal_ref: str | None

    def payload(self) -> dict[str, Any]:
        return {
            "request_fingerprint": self.request_fingerprint,
            "context_revision": self.context_revision,
            "semantic_source_revision": self.semantic_source_revision,
            "rounds_used": self.rounds_used,
            "max_rounds": self.max_rounds,
            "decisions": [decision.payload() for decision in self.decisions],
            "assumptions": list(self.assumptions),
            "latest_proposal_ref": self.latest_proposal_ref,
        }


@dataclass(frozen=True)
class ClarificationResolution:
    pending: PendingClarification
    answer: ClarificationAnswer
    decision: ClarificationDecision
    conversation: ConversationSummary


@dataclass
class _Conversation:
    session_id: str
    request_fingerprint: str
    context_revision: str
    semantic_source_revision: str
    created_at: float
    last_activity: float
    rounds_used: int = 0
    decisions: list[ClarificationDecision] = field(default_factory=list)
    assumptions: list[str] = field(default_factory=list)
    used_question_keys: set[str] = field(default_factory=set)
    latest_proposal_ref: str | None = None


@dataclass
class _SessionMemory:
    session_id: str
    last_activity: float
    conversations: dict[str, _Conversation] = field(default_factory=dict)


@dataclass(frozen=True)
class _Retired:
    session_id: str
    reason: Literal["replay", "expired"]
    retired_at: float


@dataclass
class _StoredPending:
    public: PendingClarification
    values: tuple[str | None, ...]
    assumptions_added: tuple[str, ...]
    conversation_key: str
    claimed_by: str | None = None


class ClarificationStore:
    """Thread-safe volatile store for one-shot, revision-bound questions.

    ``create_pending`` generates all option references; callers provide labels
    and optional internal values.  ``answer`` accepts only the typed answer
    shape advertised by the pending question.  The store is intentionally
    independent from ``SessionManager``: the owner calls ``drop_session`` on
    close/expiry and ``sweep_expired`` from its lifecycle loop.
    """

    def __init__(
        self,
        *,
        ttl_seconds: float = IDLE_TTL_SECONDS,
        monotonic: Callable[[], float] = time.monotonic,
        clarification_id_factory: Callable[[], str] | None = None,
        option_ref_factory: Callable[[], str] | None = None,
        max_rounds: int = MAX_ROUNDS,
        max_result_count: int = DEFAULT_MAX_RESULT_COUNT,
        max_conversations_per_session: int = MAX_CONVERSATIONS_PER_SESSION,
    ) -> None:
        if (
            isinstance(ttl_seconds, bool)
            or not isinstance(ttl_seconds, int | float)
            or ttl_seconds <= 0
            or ttl_seconds > IDLE_TTL_SECONDS
        ):
            _fail("INVALID_CONFIG", 500, "clarification TTL must be within the session TTL")
        if type(max_rounds) is not int or not 1 <= max_rounds <= MAX_ROUNDS:
            _fail("INVALID_CONFIG", 500, "clarification round budget is invalid")
        if type(max_result_count) is not int or not 1 <= max_result_count <= 100_000:
            _fail("INVALID_CONFIG", 500, "result-count bound is invalid")
        if (
            type(max_conversations_per_session) is not int
            or not 1 <= max_conversations_per_session <= 64
        ):
            _fail("INVALID_CONFIG", 500, "conversation bound is invalid")
        self._ttl = float(ttl_seconds)
        self._monotonic = monotonic
        self._new_clarification_id = clarification_id_factory or (
            lambda: "clr_" + secrets.token_urlsafe(18)
        )
        self._new_option_ref = option_ref_factory or (lambda: "opt_" + secrets.token_urlsafe(12))
        self._max_rounds = max_rounds
        self._max_result_count = max_result_count
        self._max_conversations = max_conversations_per_session
        self._sessions: dict[str, _SessionMemory] = {}
        self._pending_by_session: dict[str, _StoredPending] = {}
        self._pending_by_id: dict[str, _StoredPending] = {}
        self._retired: dict[str, _Retired] = {}
        self._revoked_sessions: dict[str, str] = {}
        self._lock = threading.RLock()

    @property
    def ttl_seconds(self) -> int:
        return int(self._ttl)

    @property
    def max_rounds(self) -> int:
        return self._max_rounds

    def _now(self, now: float | None) -> float:
        value = self._monotonic() if now is None else now
        if isinstance(value, bool) or not isinstance(value, int | float):
            _fail("INVALID_CONFIG", 500, "monotonic clock returned an invalid value")
        return float(value)

    def _new_unique(
        self,
        factory: Callable[[], str],
        *,
        name: str,
        prefix: str,
        reserved: set[str] | None = None,
    ) -> str:
        for _ in range(8):
            value = _opaque(factory(), name=name)
            if not value.startswith(prefix):
                _fail("INVALID_CONFIG", 500, f"{name} factory returned an invalid value")
            if (
                value not in self._pending_by_id
                and value not in self._retired
                and (reserved is None or value not in reserved)
            ):
                return value
        _fail("INTERNAL_ERROR", 500, f"unable to allocate a unique {name}")

    def _validate_common(
        self,
        *,
        session_id: Any,
        parent_turn_id: Any,
        request_fingerprint: Any,
        context_revision: Any,
        semantic_source_revision: Any,
    ) -> tuple[str, str, str, str, str]:
        return (
            _validate_session_id(session_id),
            _validate_turn_id(parent_turn_id),
            _fingerprint(request_fingerprint, name="request_fingerprint"),
            revision(context_revision, label="context_revision"),
            revision(semantic_source_revision, label="semantic_source_revision"),
        )

    def _retire_locked(
        self,
        clarification_id: str,
        *,
        reason: Literal["replay", "expired"],
        now: float,
    ) -> None:
        stored = self._pending_by_id.pop(clarification_id, None)
        if stored is None:
            return
        session_id = stored.public.session_id
        current = self._pending_by_session.get(session_id)
        if current is stored:
            del self._pending_by_session[session_id]
        self._retired[clarification_id] = _Retired(session_id, reason, now)
        session_retired = [
            (item_id, item)
            for item_id, item in self._retired.items()
            if item.session_id == session_id
        ]
        if len(session_retired) > MAX_RETIRED_PER_SESSION:
            oldest_id, _oldest = min(session_retired, key=lambda item: item[1].retired_at)
            self._retired.pop(oldest_id, None)

    def _drop_session_locked(self, session_id: str) -> int:
        removed = 0
        stored = self._pending_by_session.pop(session_id, None)
        if stored is not None:
            self._pending_by_id.pop(stored.public.clarification_id, None)
            removed += 1
        for clarification_id, item in list(self._retired.items()):
            if item.session_id == session_id:
                del self._retired[clarification_id]
                removed += 1
        if self._sessions.pop(session_id, None) is not None:
            removed += 1
        return removed

    def _sweep_locked(self, now: float) -> int:
        removed = 0
        for clarification_id, stored in list(self._pending_by_id.items()):
            if stored.claimed_by is None and stored.public.expires_at <= now:
                self._retire_locked(clarification_id, reason="expired", now=now)
                removed += 1
        # Retired IDs are only replay guards, never conversation memory.  Keep
        # them for at most one TTL so an unbounded long-running service cannot
        # accumulate identifiers.
        for clarification_id, item in list(self._retired.items()):
            if now - item.retired_at >= self._ttl:
                del self._retired[clarification_id]
                removed += 1
        return removed

    def _conversation_locked(
        self,
        *,
        session_id: str,
        request_fingerprint: str,
        context_revision: str,
        semantic_source_revision: str,
        now: float,
    ) -> _Conversation:
        if session_id in self._revoked_sessions:
            _fail("SESSION_REVOKED", 409, "session was revoked")
        session = self._sessions.get(session_id)
        if session is None:
            session = _SessionMemory(session_id=session_id, last_activity=now)
            self._sessions[session_id] = session
        conversation = session.conversations.get(request_fingerprint)
        if conversation is None:
            if len(session.conversations) >= self._max_conversations:
                _fail("CONVERSATION_LIMIT", 409, "session conversation capacity is exhausted")
            conversation = _Conversation(
                session_id=session_id,
                request_fingerprint=request_fingerprint,
                context_revision=context_revision,
                semantic_source_revision=semantic_source_revision,
                created_at=now,
                last_activity=now,
            )
            session.conversations[request_fingerprint] = conversation
        elif (
            conversation.context_revision != context_revision
            or conversation.semantic_source_revision != semantic_source_revision
        ):
            _fail("CLARIFICATION_STALE", 409, "clarification revisions are stale")
        session.last_activity = now
        conversation.last_activity = now
        return conversation

    @staticmethod
    def _add_assumptions_locked(
        conversation: _Conversation,
        assumptions: Sequence[str],
    ) -> tuple[str, ...]:
        """Merge assumptions only after the question itself is admissible."""

        cleaned_assumptions = [
            _bounded_text(item, name="assumption", max_bytes=MAX_ASSUMPTION_BYTES)
            for item in assumptions
        ]
        additions = tuple(
            item
            for item in dict.fromkeys(cleaned_assumptions)
            if item not in conversation.assumptions
        )
        if len(conversation.assumptions) + len(additions) > MAX_ROUNDS:
            _fail("ASSUMPTION_LIMIT", 409, "assumption summary is bounded")
        conversation.assumptions.extend(additions)
        return additions

    def _summary_locked(self, conversation: _Conversation) -> ConversationSummary:
        return ConversationSummary(
            session_id=conversation.session_id,
            request_fingerprint=conversation.request_fingerprint,
            context_revision=conversation.context_revision,
            semantic_source_revision=conversation.semantic_source_revision,
            rounds_used=conversation.rounds_used,
            max_rounds=self._max_rounds,
            decisions=tuple(conversation.decisions),
            assumptions=tuple(conversation.assumptions),
            latest_proposal_ref=conversation.latest_proposal_ref,
        )

    def create_pending(
        self,
        *,
        session_id: str,
        parent_turn_id: str,
        request_fingerprint: str,
        context_revision: str,
        semantic_source_revision: str,
        kind: str,
        question: str,
        options: Sequence[ClarificationChoice | str] = (),
        min_value: int = 1,
        max_value: int | None = None,
        question_key: str | None = None,
        assumptions: Sequence[str] = (),
        conversation_key: str | None = None,
        now: float | None = None,
    ) -> PendingClarification:
        """Create one server-owned question and return its safe public view."""

        session_id, parent_turn_id, request_fingerprint, context_revision, semantic_revision = (
            self._validate_common(
                session_id=session_id,
                parent_turn_id=parent_turn_id,
                request_fingerprint=request_fingerprint,
                context_revision=context_revision,
                semantic_source_revision=semantic_source_revision,
            )
        )
        conversation_key = _fingerprint(
            request_fingerprint if conversation_key is None else conversation_key,
            name="conversation_key",
        )
        if kind not in CLARIFICATION_KINDS:
            _fail("INVALID_SCHEMA", 400, "clarification kind is unsupported")
        question = _bounded_text(question, name="question", max_bytes=MAX_QUESTION_BYTES)
        key = question_key or "auto:" + sha256(f"{kind}\0{question}".encode()).hexdigest()
        key = _question_key(key)
        clock = self._now(now)
        with self._lock:
            self._sweep_locked(clock)
            if session_id in self._revoked_sessions:
                _fail("SESSION_REVOKED", 409, "session was revoked")
            if session_id in self._pending_by_session:
                _fail("CLARIFICATION_PENDING", 409, "session already has a pending clarification")
            cleaned_options: list[ClarificationChoice] = []
            catalog_reference_mode = kind == "catalog" and len(options) > MAX_OPTIONS
            if kind in OPTION_KINDS:
                maximum = MAX_CATALOG_REFERENCES if catalog_reference_mode else MAX_OPTIONS
                if not 2 <= len(options) <= maximum:
                    _fail(
                        "INVALID_SCHEMA",
                        400,
                        (
                            "catalog clarification exceeds the catalog roster bound"
                            if catalog_reference_mode
                            else "option clarification requires two to five options"
                        ),
                    )
                for option in options:
                    if isinstance(option, str):
                        option = ClarificationChoice(option)
                    if not isinstance(option, ClarificationChoice):
                        _fail("INVALID_SCHEMA", 400, "clarification options are invalid")
                    cleaned_options.append(option)
                if not catalog_reference_mode and len(
                    {item.label for item in cleaned_options}
                ) != len(cleaned_options):
                    _fail("INVALID_SCHEMA", 400, "clarification option labels must be distinct")
                if catalog_reference_mode:
                    if any(
                        item.catalog is None or item.value is None or item.value != item.catalog
                        for item in cleaned_options
                    ):
                        _fail(
                            "INVALID_SCHEMA",
                            400,
                            "catalog roster options require one exact catalog identity",
                        )
                    catalog_identities = [item.catalog for item in cleaned_options]
                    distinct_identities = {
                        item.casefold() for item in catalog_identities if item is not None
                    }
                    if len(distinct_identities) != len(catalog_identities):
                        _fail("INVALID_SCHEMA", 400, "catalog roster identities must be distinct")
            else:
                if options:
                    _fail("INVALID_SCHEMA", 400, "result-count clarification cannot have options")
                if type(min_value) is not int or min_value < 1:
                    _fail("INVALID_SCHEMA", 400, "result-count minimum is invalid")
                effective_max = self._max_result_count if max_value is None else max_value
                if (
                    type(effective_max) is not int
                    or effective_max < min_value
                    or effective_max > self._max_result_count
                ):
                    _fail("INVALID_SCHEMA", 400, "result-count maximum is invalid")
                max_value = effective_max

            conversation = self._conversation_locked(
                session_id=session_id,
                request_fingerprint=conversation_key,
                context_revision=context_revision,
                semantic_source_revision=semantic_revision,
                now=clock,
            )
            if conversation.rounds_used >= self._max_rounds:
                _fail("CLARIFICATION_BUDGET_EXCEEDED", 409, "clarification budget is exhausted")
            if key in conversation.used_question_keys:
                _fail("CLARIFICATION_REPEAT", 409, "clarification question was already asked")
            assumptions_added = self._add_assumptions_locked(conversation, assumptions)

            clarification_id = self._new_unique(
                self._new_clarification_id,
                name="clarification_id",
                prefix="clr_",
            )
            public_options: list[ClarificationOption] = []
            values: list[str | None] = []
            option_refs: set[str] = set()
            for option in cleaned_options:
                if catalog_reference_mode:
                    values.append(option.value)
                    continue
                option_ref = self._new_unique(
                    self._new_option_ref,
                    name="option_ref",
                    prefix="opt_",
                    reserved=option_refs,
                )
                option_refs.add(option_ref)
                public_options.append(
                    ClarificationOption(
                        option_ref,
                        option.label,
                        option.description,
                        option.catalog,
                    )
                )
                values.append(option.value)
            pending = PendingClarification(
                clarification_id=clarification_id,
                session_id=session_id,
                parent_turn_id=parent_turn_id,
                request_fingerprint=request_fingerprint,
                kind=kind,  # type: ignore[arg-type]
                question_key=key,
                question=question,
                options=tuple(public_options),
                context_revision=context_revision,
                semantic_source_revision=semantic_revision,
                round_index=conversation.rounds_used + 1,
                max_rounds=self._max_rounds,
                expires_at=clock + self._ttl,
                catalog_refs=(
                    tuple(item.catalog for item in cleaned_options if item.catalog is not None)
                    if catalog_reference_mode
                    else ()
                ),
                min_value=min_value if kind == "result_count" else None,
                max_value=max_value if kind == "result_count" else None,
            )
            stored = _StoredPending(
                pending,
                tuple(values),
                assumptions_added,
                conversation_key,
            )
            self._pending_by_session[session_id] = stored
            self._pending_by_id[clarification_id] = stored
            conversation.used_question_keys.add(key)
            return pending

    def answer(
        self,
        *,
        session_id: str,
        clarification_id: str,
        request_fingerprint: str,
        context_revision: str,
        semantic_source_revision: str,
        answer: Mapping[str, Any],
        expected_kind: str | None = None,
        claim_owner: str | None = None,
        now: float | None = None,
    ) -> ClarificationResolution:
        """Consume a pending answer atomically, returning its resolved decision."""

        session_id = _validate_session_id(session_id)
        clarification_id = _opaque(clarification_id, name="clarification_id")
        request_fingerprint = _fingerprint(request_fingerprint, name="request_fingerprint")
        context_revision = revision(context_revision, label="context_revision")
        semantic_revision = revision(semantic_source_revision, label="semantic_source_revision")
        if claim_owner is not None:
            claim_owner = _validate_turn_id(claim_owner)
        clock = self._now(now)
        with self._lock:
            stored = self._pending_by_id.get(clarification_id)
            if stored is None:
                retired = self._retired.get(clarification_id)
                if retired is None:
                    self._sweep_locked(clock)
                    retired = self._retired.get(clarification_id)
                if retired is not None and retired.session_id != session_id:
                    _fail(
                        "CLARIFICATION_CROSS_SESSION",
                        403,
                        "clarification belongs to another session",
                    )
                if retired is not None and retired.reason == "replay":
                    _fail("CLARIFICATION_REPLAY", 409, "clarification was already consumed")
                if retired is not None and retired.reason == "expired":
                    _fail("CLARIFICATION_EXPIRED", 410, "clarification has expired")
                _fail("CLARIFICATION_UNKNOWN", 404, "clarification is unknown")
            pending = stored.public
            if pending.session_id != session_id:
                _fail(
                    "CLARIFICATION_CROSS_SESSION", 403, "clarification belongs to another session"
                )
            if stored.claimed_by is not None and stored.claimed_by != claim_owner:
                _fail("CLARIFICATION_CLAIMED", 409, "clarification answer is already admitted")
            if claim_owner is not None and stored.claimed_by != claim_owner:
                _fail("CLARIFICATION_CLAIM_UNAVAILABLE", 409, "clarification claim is unavailable")
            if stored.claimed_by is None and pending.expires_at <= clock:
                self._retire_locked(clarification_id, reason="expired", now=clock)
                _fail("CLARIFICATION_EXPIRED", 410, "clarification has expired")
            if pending.request_fingerprint != request_fingerprint:
                _fail("CLARIFICATION_REQUEST_MISMATCH", 409, "clarification request differs")
            if expected_kind is not None and expected_kind != pending.kind:
                _fail("CLARIFICATION_WRONG_KIND", 409, "clarification kind differs")
            if pending.context_revision != context_revision:
                _fail("CLARIFICATION_STALE_CONTEXT", 409, "clarification context is stale")
            if pending.semantic_source_revision != semantic_revision:
                _fail("CLARIFICATION_STALE_SEMANTIC", 409, "clarification semantic source is stale")
            if not isinstance(answer, Mapping):
                _fail("INVALID_SCHEMA", 400, "clarification answer must be an object")
            expected_field = (
                "integer"
                if pending.kind == "result_count"
                else "text"
                if pending.catalog_refs
                else "option_ref"
            )
            if set(answer) != {expected_field}:
                _fail("INVALID_SCHEMA", 400, "clarification answer has an invalid field roster")
            resolved_value: str | None = None
            label: str | None = None
            integer: int | None = None
            text: str | None = None
            if pending.kind == "result_count":
                integer = answer[expected_field]
                if (
                    type(integer) is not int
                    or pending.min_value is None
                    or pending.max_value is None
                    or not pending.min_value <= integer <= pending.max_value
                ):
                    _fail("CLARIFICATION_VALUE_OUT_OF_RANGE", 422, "result count is out of range")
            elif pending.catalog_refs:
                candidate = clarification_text(answer[expected_field])
                if candidate not in pending.catalog_refs:
                    _fail(
                        "CLARIFICATION_CATALOG_UNKNOWN",
                        422,
                        "catalog reference is not valid for this question",
                    )
                selected_index = pending.catalog_refs.index(candidate)
                resolved_value = stored.values[selected_index]
                text = candidate
                label = candidate
            else:
                option_ref = answer[expected_field]
                if not isinstance(option_ref, str):
                    _fail("INVALID_SCHEMA", 400, "option_ref must be a string")
                selected_index = next(
                    (
                        index
                        for index, option in enumerate(pending.options)
                        if option.option_ref == option_ref
                    ),
                    None,
                )
                if selected_index is None:
                    _fail(
                        "CLARIFICATION_OPTION_UNKNOWN",
                        422,
                        "option_ref is not valid for this question",
                    )
                assert selected_index is not None
                resolved_value = stored.values[selected_index]
                label = pending.options[selected_index].label
            typed_answer = ClarificationAnswer(
                kind=pending.kind,
                option_ref=answer.get("option_ref"),
                integer=integer,
                text=text,
                resolved_value=resolved_value,
            )
            decision = ClarificationDecision(
                kind=pending.kind,
                question_key=pending.question_key,
                round_index=pending.round_index,
                answer=typed_answer,
                label=label,
            )
            conversation = self._sessions[pending.session_id].conversations[stored.conversation_key]
            self._retire_locked(clarification_id, reason="replay", now=clock)
            conversation.rounds_used += 1
            conversation.decisions.append(decision)
            conversation.last_activity = clock
            self._sessions[pending.session_id].last_activity = clock
            return ClarificationResolution(
                pending=pending,
                answer=typed_answer,
                decision=decision,
                conversation=self._summary_locked(conversation),
            )

    def validate_answer(
        self,
        *,
        session_id: str,
        clarification_id: str,
        request_fingerprint: str,
        context_revision: str,
        semantic_source_revision: str,
        answer: Mapping[str, Any],
        claim_owner: str | None = None,
        now: float | None = None,
    ) -> None:
        """Validate an answer synchronously without consuming its one-shot ID."""

        session_id = _validate_session_id(session_id)
        clarification_id = _opaque(clarification_id, name="clarification_id")
        request_fingerprint = _fingerprint(request_fingerprint, name="request_fingerprint")
        context_revision = revision(context_revision, label="context_revision")
        semantic_revision = revision(semantic_source_revision, label="semantic_source_revision")
        if claim_owner is not None:
            claim_owner = _validate_turn_id(claim_owner)
        clock = self._now(now)
        with self._lock:
            stored = self._pending_by_id.get(clarification_id)
            if stored is None:
                retired = self._retired.get(clarification_id)
                if retired is None:
                    self._sweep_locked(clock)
                    retired = self._retired.get(clarification_id)
                if retired is not None and retired.session_id != session_id:
                    _fail(
                        "CLARIFICATION_CROSS_SESSION",
                        403,
                        "clarification belongs to another session",
                    )
                if retired is not None and retired.reason == "replay":
                    _fail("CLARIFICATION_REPLAY", 409, "clarification was already consumed")
                if retired is not None and retired.reason == "expired":
                    _fail("CLARIFICATION_EXPIRED", 410, "clarification has expired")
                _fail("CLARIFICATION_UNKNOWN", 404, "clarification is unknown")
            pending = stored.public
            if pending.session_id != session_id:
                _fail(
                    "CLARIFICATION_CROSS_SESSION", 403, "clarification belongs to another session"
                )
            if stored.claimed_by is not None and stored.claimed_by != claim_owner:
                _fail(
                    "CLARIFICATION_CLAIMED",
                    409,
                    "clarification answer is already admitted",
                )
            if stored.claimed_by is None and pending.expires_at <= clock:
                self._retire_locked(clarification_id, reason="expired", now=clock)
                _fail("CLARIFICATION_EXPIRED", 410, "clarification has expired")
            if pending.request_fingerprint != request_fingerprint:
                _fail("CLARIFICATION_REQUEST_MISMATCH", 409, "clarification request differs")
            if pending.context_revision != context_revision:
                _fail("CLARIFICATION_STALE_CONTEXT", 409, "clarification context is stale")
            if pending.semantic_source_revision != semantic_revision:
                _fail("CLARIFICATION_STALE_SEMANTIC", 409, "clarification semantic source is stale")
            if not isinstance(answer, Mapping):
                _fail("INVALID_SCHEMA", 400, "clarification answer must be an object")
            expected_field = (
                "integer"
                if pending.kind == "result_count"
                else "text"
                if pending.catalog_refs
                else "option_ref"
            )
            if set(answer) != {expected_field}:
                _fail("INVALID_SCHEMA", 400, "clarification answer has an invalid field roster")
            if pending.kind == "result_count":
                integer = answer[expected_field]
                if (
                    type(integer) is not int
                    or pending.min_value is None
                    or pending.max_value is None
                    or not pending.min_value <= integer <= pending.max_value
                ):
                    _fail("CLARIFICATION_VALUE_OUT_OF_RANGE", 422, "result count is out of range")
            elif pending.catalog_refs:
                candidate = clarification_text(answer[expected_field])
                if candidate not in pending.catalog_refs:
                    _fail(
                        "CLARIFICATION_CATALOG_UNKNOWN",
                        422,
                        "catalog reference is not valid for this question",
                    )
            else:
                option_ref = answer[expected_field]
                if not isinstance(option_ref, str):
                    _fail("INVALID_SCHEMA", 400, "option_ref must be a string")
                if not any(option.option_ref == option_ref for option in pending.options):
                    _fail(
                        "CLARIFICATION_OPTION_UNKNOWN",
                        422,
                        "option_ref is not valid for this question",
                    )
            if claim_owner is not None:
                stored.claimed_by = claim_owner

    def release_answer_claim(self, *, session_id: str, owner: str) -> bool:
        """Release one queued answer claim so the same pending question can be retried."""

        session_id = _validate_session_id(session_id)
        owner = _validate_turn_id(owner)
        with self._lock:
            stored = self._pending_by_session.get(session_id)
            if stored is None or stored.claimed_by != owner:
                return False
            stored.claimed_by = None
            return True

    def conversation(
        self,
        *,
        session_id: str,
        request_fingerprint: str,
        now: float | None = None,
    ) -> ConversationSummary:
        session_id = _validate_session_id(session_id)
        request_fingerprint = _fingerprint(request_fingerprint, name="request_fingerprint")
        clock = self._now(now)
        with self._lock:
            self._sweep_locked(clock)
            session = self._sessions.get(session_id)
            conversation = session.conversations.get(request_fingerprint) if session else None
            if conversation is None:
                _fail("CONVERSATION_UNKNOWN", 404, "conversation is unknown")
            assert conversation is not None
            return self._summary_locked(conversation)

    def server_context(
        self,
        *,
        session_id: str,
        request_fingerprint: str,
        now: float | None = None,
    ) -> dict[str, Any] | None:
        """Return all bounded decisions for this logical request, in process only.

        Public summaries deliberately omit internal catalog/value identities.
        The orchestrator still needs those identities to resume a dialogue that
        legitimately requires more than one question.  This method keeps that
        authority server-side and never serializes it directly on the wire.
        """

        session_id = _validate_session_id(session_id)
        request_fingerprint = _fingerprint(request_fingerprint, name="request_fingerprint")
        clock = self._now(now)
        with self._lock:
            self._sweep_locked(clock)
            session = self._sessions.get(session_id)
            conversation = session.conversations.get(request_fingerprint) if session else None
            if conversation is None:
                return None
            summary = self._summary_locked(conversation)
            return {
                "conversation": summary.payload(),
                "decisions": [
                    {
                        **decision.payload(),
                        "resolved_value": decision.answer.resolved_value,
                    }
                    for decision in conversation.decisions
                ],
            }

    def set_latest_proposal(
        self,
        *,
        session_id: str,
        request_fingerprint: str,
        proposal_ref: str,
        now: float | None = None,
    ) -> ConversationSummary:
        session_id = _validate_session_id(session_id)
        request_fingerprint = _fingerprint(request_fingerprint, name="request_fingerprint")
        proposal_ref = _opaque(proposal_ref, name="proposal_ref", max_bytes=MAX_PROPOSAL_REF_BYTES)
        clock = self._now(now)
        with self._lock:
            self._sweep_locked(clock)
            session = self._sessions.get(session_id)
            conversation = session.conversations.get(request_fingerprint) if session else None
            if conversation is None:
                _fail("CONVERSATION_UNKNOWN", 404, "conversation is unknown")
            assert conversation is not None
            conversation.latest_proposal_ref = proposal_ref
            conversation.last_activity = clock
            session.last_activity = clock
            return self._summary_locked(conversation)

    def drop_session(self, session_id: str, *, revocation_owner: str | None = None) -> int:
        session_id = _validate_session_id(session_id)
        if revocation_owner is not None:
            revocation_owner = _validate_turn_id(revocation_owner)
        with self._lock:
            removed = self._drop_session_locked(session_id)
            if revocation_owner is not None:
                self._revoked_sessions[session_id] = revocation_owner
            return removed

    def release_revocation_guard(self, session_id: str, *, owner: str) -> None:
        """Release the transient guard after the revoked session's worker exits."""

        session_id = _validate_session_id(session_id)
        owner = _validate_turn_id(owner)
        with self._lock:
            if self._revoked_sessions.get(session_id) == owner:
                self._revoked_sessions.pop(session_id, None)

    def discard_pending_for_turn(self, *, session_id: str, parent_turn_id: str) -> bool:
        """Rollback only a pending question that was hidden by turn cancellation.

        Previously accepted decisions remain in the volatile session.  The
        question key and only the assumptions introduced with this question
        are released, allowing a deliberate retry of the same logical request.
        """

        session_id = _validate_session_id(session_id)
        parent_turn_id = _validate_turn_id(parent_turn_id)
        with self._lock:
            stored = self._pending_by_session.get(session_id)
            if stored is None or stored.public.parent_turn_id != parent_turn_id:
                return False

            pending = stored.public
            self._pending_by_session.pop(session_id, None)
            self._pending_by_id.pop(pending.clarification_id, None)
            session = self._sessions.get(session_id)
            conversation = session.conversations.get(stored.conversation_key) if session else None
            if conversation is not None:
                conversation.used_question_keys.discard(pending.question_key)
                for assumption in stored.assumptions_added:
                    if assumption in conversation.assumptions:
                        conversation.assumptions.remove(assumption)
                if (
                    conversation.rounds_used == 0
                    and not conversation.decisions
                    and not conversation.assumptions
                    and not conversation.used_question_keys
                    and conversation.latest_proposal_ref is None
                ):
                    session.conversations.pop(stored.conversation_key, None)
            if session is not None and not session.conversations:
                self._sessions.pop(session_id, None)
            return True

    def sweep_expired(self, *, now: float | None = None) -> int:
        clock = self._now(now)
        with self._lock:
            return self._sweep_locked(clock)

    def metrics(self) -> dict[str, int]:
        with self._lock:
            return {
                "sessions": len(self._sessions),
                "conversations": sum(len(item.conversations) for item in self._sessions.values()),
                "pending": len(self._pending_by_id),
                "retired": len(self._retired),
                "decisions": sum(
                    len(conversation.decisions)
                    for session in self._sessions.values()
                    for conversation in session.conversations.values()
                ),
                "assumptions": sum(
                    len(conversation.assumptions)
                    for session in self._sessions.values()
                    for conversation in session.conversations.values()
                ),
            }

    def has_pending(self, session_id: str) -> bool:
        session_id = _validate_session_id(session_id)
        with self._lock:
            self._sweep_locked(self._now(None))
            return session_id in self._pending_by_session

    def touch_session(self, session_id: str, *, now: float | None = None) -> None:
        """Keep existing volatile memory aligned with an authenticated chat turn."""

        session_id = _validate_session_id(session_id)
        clock = self._now(now)
        with self._lock:
            self._sweep_locked(clock)
            if session_id in self._revoked_sessions:
                _fail("SESSION_REVOKED", 409, "session was revoked")
            session = self._sessions.get(session_id)
            if session is not None:
                session.last_activity = clock

    aggregate_metrics = metrics

    def clear(self) -> int:
        with self._lock:
            removed = (
                len(self._sessions)
                + len(self._pending_by_id)
                + len(self._retired)
                + len(self._revoked_sessions)
            )
            self._sessions.clear()
            self._pending_by_session.clear()
            self._pending_by_id.clear()
            self._retired.clear()
            self._revoked_sessions.clear()
            return removed
